apiVersion: v1
kind: Service
metadata:
  name: flask-configmap-service
spec:
  ports:
  - port: 80
    targetPort: flask-port
    protocol: TCP
  selector:
    app: flask-configmap
  type: LoadBalancer
